# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-18 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ingredient',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='recipeitem',
            old_name='ingredient',
            new_name='food',
        ),
    ]
