# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-14 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='mass_equivalent',
        ),
    ]
