# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='price',
            name='product',
        ),
        migrations.RemoveField(
            model_name='price',
            name='revision_ptr',
        ),
        migrations.RemoveField(
            model_name='productname',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productname',
            name='revision_ptr',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='ean_code',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='ProductName',
        ),
        migrations.DeleteModel(
            name='Revision',
        ),
    ]
