# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20170311_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='price_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='quality_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='sustainability_weight',
            field=models.IntegerField(default=0),
        ),
    ]
