# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-04 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180618_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='mass_equivalent',
            field=models.IntegerField(default=0),
        ),
    ]
