# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-14 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_recipeitem_unit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Score',
            new_name='ProductScore',
        ),
    ]
