# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-07 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_food_mass_equivalent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='provides',
        ),
    ]
