# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20170311_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.IntegerField(null=True)),
                ('social', models.IntegerField(null=True)),
                ('animals', models.IntegerField(null=True)),
                ('personal_health', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='scores',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Score'),
        ),
    ]
