# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20170311_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreferences',
            old_name='quality_weight',
            new_name='animals_weight',
        ),
        migrations.RenameField(
            model_name='userpreferences',
            old_name='sustainability_weight',
            new_name='environment_weight',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='personal_health_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='social_weight',
            field=models.IntegerField(default=0),
        ),
    ]
