# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-07 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20181017_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('image_url', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='themes',
            field=models.ManyToManyField(to='product.ScoreTheme'),
        ),
        migrations.AddField(
            model_name='product',
            name='certificates',
            field=models.ManyToManyField(to='product.Certificate'),
        ),
    ]
