# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-07 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20181107_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carbohydrates_in_g_per_100_g',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='energy_in_kj_per_100_g',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fat_saturated_in_g_per_100_g',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fat_total_in_g_per_100_g',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fiber_in_g_per_100_g',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='protein_in_g_per_100_g',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='salt_in_g_per_100_g',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sugar_in_g_per_100_g',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
