# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20170311_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumb_url',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
