# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_thumb_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount_in_gram',
            field=models.IntegerField(null=True),
        ),
    ]
