# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-07 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='usages',
            field=models.ManyToManyField(to='product.ProductUsage'),
        ),
    ]
