# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 11:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20170312_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author_if_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
