# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-07 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_usages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
                ('questionmark_id', models.IntegerField(default=0)),
                ('ean_code', models.CharField(blank=True, max_length=25, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Brand')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='score_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ScoreCreator'),
        ),
    ]
