# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20170312_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('-', '-'), ('g', 'g'), ('ml', 'ml')], default='-', max_length=20),
        ),
    ]
