# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-07 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20181107_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorecreator',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='scorecreator',
            name='ean_code',
        ),
        migrations.RemoveField(
            model_name='scorecreator',
            name='name',
        ),
        migrations.RemoveField(
            model_name='scorecreator',
            name='questionmark_id',
        ),
        migrations.AddField(
            model_name='scorecreator',
            name='production_in_ton_per_ha',
            field=models.FloatField(default=0),
        ),
    ]
