# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20170312_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('-', '-'), ('g', 'g'), ('ml', 'ml')], default='-', max_length=5),
        ),
    ]
