# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-07 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20181107_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecreator',
            name='killed_animal_iq_points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='scorecreator',
            name='production_in_ton_per_ha',
            field=models.FloatField(default=5),
        ),
    ]
