# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20170312_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('-', 'st.'), ('g', 'g'), ('ml', 'ml'), ('el', 'el')], default='-', max_length=5),
        ),
    ]
