# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-07 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20181107_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecreator',
            name='sources',
            field=models.TextField(blank=True),
        ),
    ]
