# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20170319_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount_in_gram',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('-', 'st.'), ('g', 'g'), ('ml', 'ml'), ('el', 'el')], default='-', max_length=5),
        ),
    ]
