# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-07 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_scorecreator_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='equiv_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='score_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ScoreCreator'),
        ),
    ]
