# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20170320_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='questionmark_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
