# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-17 17:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_scorecreator_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecreator',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
