# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20170325_1324'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAtShop',
            new_name='ProductPrice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.AddField(
            model_name='product',
            name='prices',
            field=models.ManyToManyField(through='product.ProductPrice', to='product.Shop'),
        ),
    ]
