# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-15 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_productprice_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('-', 'st.'), ('g', 'g'), ('ml', 'ml'), ('el', 'el'), ('tl', 'tl')], default='-', max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('-', 'st.'), ('g', 'g'), ('ml', 'ml'), ('el', 'el'), ('tl', 'tl')], default='-', max_length=5),
        ),
    ]
