# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-16 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20171216_1209'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Ingredient',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='recipeitem',
            old_name='category',
            new_name='ingredient',
        ),
    ]
