# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-18 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_rename_food_names_lowercase'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='waiting_time_in_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='unit',
            field=models.CharField(choices=[('-', 'st.'), ('g', 'g'), ('ml', 'ml'), ('el', 'el'), ('tl', 'tl')], default='g', max_length=5),
        ),
    ]
