# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-16 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20171216_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='animals_weight',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='environment_weight',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='personal_health_weight',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='price_weight',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='social_weight',
            field=models.IntegerField(default=50),
        ),
    ]
