# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-13 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_supplyitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='animal_harm',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='land_use_m2',
            field=models.IntegerField(default=50),
        ),
    ]
