# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-13 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20190113_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='prep_time',
            field=models.IntegerField(default=50),
        ),
    ]
