# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-21 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20190120_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpropertytype',
            name='value_type',
            field=models.CharField(choices=[('BOOL', 'Ja of Nee'), ('FLOAT', 'Getal')], default='BOOL', max_length=5),
            preserve_default=False,
        ),
    ]
