# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-21 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_foodpropertytype_value_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpropertytype',
            name='combine_strategy',
            field=models.CharField(choices=[('OR', 'Logische of'), ('AND', 'Logische en')], max_length=5),
        ),
    ]
