# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-21 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20190122_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpropertytype',
            name='scale_strategy',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
