# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-22 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_foodpropertytype_scale_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodproperty',
            name='value_float',
            field=models.FloatField(default=None, null=True),
        ),
    ]
