# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-22 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_foodproperty_value_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodproperty',
            name='source',
            field=models.TextField(blank=True),
        ),
    ]
