# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-24 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_foodproperty_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpropertytype',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
