# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-02 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_foodpropertytype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpropertytype',
            name='scoring_scaling',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='foodpropertytype',
            name='scoring_transformation_strategy',
            field=models.CharField(choices=[('NONE', 'Geen transformatie'), ('INV', 'Inverteren')], default='NONE', max_length=5),
        ),
    ]
