# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionmark', '0003_jumboquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='AHQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_product_name', models.CharField(max_length=256)),
                ('json', models.TextField()),
            ],
        ),
    ]
