# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionmark', '0004_ahquery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionmarkquery',
            old_name='q_product_name',
            new_name='params_as_string',
        ),
    ]
