# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-15 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AHQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_product_name', models.CharField(max_length=256)),
                ('json', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JumboQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_product_name', models.CharField(max_length=256)),
                ('html', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionMarkQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params_as_string', models.CharField(max_length=256)),
                ('json', models.TextField()),
            ],
        ),
    ]
