# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-07 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181024_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionmarkEntry',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('brand', models.CharField(max_length=256)),
                ('thumb_url', models.CharField(max_length=256)),
                ('date', models.DateTimeField(auto_now=True)),
                ('score_environment', models.IntegerField(blank=True, default=None, null=True)),
                ('score_social', models.IntegerField(blank=True, default=None, null=True)),
                ('score_animals', models.IntegerField(blank=True, default=None, null=True)),
                ('score_personal_health', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
