# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-07 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_questionmarkentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmarkentry',
            name='score_personal_health',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
