# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-07 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181107_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionmarkCertificate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('image_url', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionmarkTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='questionmarkcertificate',
            name='themes',
            field=models.ManyToManyField(to='api.QuestionmarkTheme'),
        ),
        migrations.AddField(
            model_name='questionmarkentry',
            name='certificates',
            field=models.ManyToManyField(to='api.QuestionmarkCertificate'),
        ),
    ]
